# Generated by Django 3.1.5 on 2021-01-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210124_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='타이틀의 내용을 간략화 시켜줍니다.', max_length=100, unique=True, verbose_name='SLUG'),
        ),
    ]
